#!/bin/bash

function helpinfo(){
	cat << HELP

	setpool --set grid etcd config

	USAGE: ./setpool ippoolinfo etcdendpoints

	EXAMPLE: ./setpool 172.16.30_150-250/24 https://172.16.30.100:2379,https://172.16.30.101:2379

	OPTIONS: -h HELP TEXT
HELP
}

if [ $# -eq 0 ];then
	helpinfo
	exit 1
fi

if [ $# -eq 1 ] && [ $1 == "help" ];then
	helpinfo
	exit 0
fi

if [ $# -eq 1 ] && [ $1 == "version" ];then
        echo "v3"
        exit 0
fi

echo $1 |grep "[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\_[0-9]\{1,3\}\-[0-9]\{1,3\}\/[0-9]\{1,2\}" >> /dev/null

if [ $? -ne 0 ];then
	echo -e "\033[1;31m ----------------------------------------------- \033[0m"
	echo -e "\033[1;31m - ippoolinfo format error, please check again - \033[0m"
	echo -e "\033[1;31m -    use ./setpool help print right format    - \033[0m"
	echo -e "\033[1;31m ----------------------------------------------- \033[0m"
	exit 1
fi

ippoolname=$1

ETCDCTL_API=3 etcdctl --key="/etc/kubernetes/pki/etcd/server.key" --cacert="/etc/kubernetes/pki/etcd/ca.crt" --cert="/etc/kubernetes/pki/etcd/server.crt" --endpoints=$2 endpoint health |grep successfully >> /dev/null
if [ $? -ne 0 ];then
	echo -e "\033[1;31m can't connect etcd,please check etcdendpoints config again or check etcd server health \033[0m"
	exit 1
fi
    
time=`date "+%Y-%m-%dT%H:%M:%SZ"`

uid=`cat /proc/sys/kernel/random/uuid`

gid=`echo -n $1 | base64 | md5sum | sha256sum | head -c 32`

ETCDCTL_API=3 etcdctl --key="/etc/kubernetes/pki/etcd/server.key" --cacert="/etc/kubernetes/pki/etcd/ca.crt" --cert="/etc/kubernetes/pki/etcd/server.crt" --endpoints=$2 get /calico/resources/v3/projectcalico.org/clusterinformations/default |grep datastoreReady >> /dev/null

if [ $? -ne 0 ];then

ETCDCTL_API=3 etcdctl --key="/etc/kubernetes/pki/etcd/server.key" --cacert="/etc/kubernetes/pki/etcd/ca.crt" --cert="/etc/kubernetes/pki/etcd/server.crt" --endpoints=$2 put /calico/resources/v3/projectcalico.org/clusterinformations/default "{\"kind\":\"ClusterInformation\",\"apiVersion\":\"projectcalico.org/v3\",\"metadata\":{\"name\":\"default\",\"uid\":\"$uid\",\"creationTimestamp\":\"$time\"},\"spec\":{\"clusterGUID\":\"$gid\",\"clusterType\":\"k8s\",\"calicoVersion\":\"v3.1.3\",\"datastoreReady\":true}}"
fi

poolname=`echo $1 | sed 's/\/24//g'`

poolnamekey=`echo "/calico/resources/v3/projectcalico.org/ippools/$poolname"`

cidr=`echo $1 | sed 's/\-[0-9]\{1,3\}//g'|sed 's/\_/\./g'`

ETCDCTL_API=3 etcdctl --key="/etc/kubernetes/pki/etcd/server.key" --cacert="/etc/kubernetes/pki/etcd/ca.crt" --cert="/etc/kubernetes/pki/etcd/server.crt" --endpoints=$2 put $poolnamekey "{\"kind\":\"IPPool\",\"apiVersion\":\"projectcalico.org/v3\",\"metadata\":{\"name\":\"$poolname\",\"uid\":\"$uid\",\"creationTimestamp\":\"$time\"},\"spec\":{\"cidr\":\"$cidr\",\"ipipMode\":\"Never\",\"natOutgoing\":true}}"

echo "COMPLETE"
